#!/usr/bin/env bash


#  #--------------------------------------------------------------------------------------------------------------------------
# ?                                                   QUESTION HEADER
#  - Drive path 
#  - EFI partition path
#  - Root partition
#  - Hostname (username)

#--------------------------------------------------------------------------------------------------------------------------



#  //TODO - add mosque icu header aswell near this defos

#  sh logo sh

# mesage user installing defoos
# echo "Installing DefOS..."



sed -i "s/^#ParallelDownloads = 5$/ParallelDownloads = 15/" /etc/pacman.conf
pacman --noconfirm -Sy archlinux-keyring networkmanager
loadkeys us
timedatectl set-ntp true
lsblk

# 


echo "Enter the drive: "
read drive
cfdisk $drive

# 

echo "Enter EFI partition: "
# //TODO -  make the efi a variable so its reused
read efipartition
mkfs.vfat -F 32 $efipartition

#  //LINK - 
echo "Enter the root partition: "
read rootpartition
mkfs.ext4 $rootpartition
mount $rootpartition /mnt


pacstrap /mnt base base-devel linux linux-firmware
genfstab -U /mnt >>/mnt/etc/fstab
sed '1,/^#part2$/d' $(basename $0) >/mnt/arch_install2.sh
chmod +x /mnt/arch_install2.sh
arch-chroot /mnt ./arch_install2.sh
exit

#part2

printf '\033c'
pacman -S --noconfirm sed
ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
hwclock --systohc
echo "en_US.UTF-8 UTF-8" >>/etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >/etc/locale.conf
echo "KEYMAP=us" >/etc/vconsole.conf

#  //LINK - 
echo "Hostname: "
read hostname
echo $hostname >/etc/hostname


echo "127.0.0.1       localhost" >>/etc/hosts
echo "::1             localhost" >>/etc/hosts
echo "127.0.1.1       $hostname.localdomain $hostname" >>/etc/hosts
mkinitcpio -P
passwd
pacman --noconfirm -S grub efibootmgr os-prober


# //TODO - identidy if the user is a uefi or efi boot

#  //
echo "Enter EFI partition: "
read efipartition
mkdir /boot/efi
mount $efipartition /boot/efi
# //FIXME -  This is redundant code should reuse variables


grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB
sed -i 's/quiet/pci=noaer/g' /etc/default/grub
sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/g' /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg

pacman -S --noconfirm xorg-server xorg-xinit xorg-xkill xorg-xsetroot xorg-xbacklight xorg-xprop xorg-xrandr xorg-xset xorgproto xterm xwallpaper xxhash \
	noto-fonts noto-fonts-emoji noto-fonts-cjk ttf-jetbrains-mono ttf-joypixels ttf-font-awesome ttf-dejavu \
	sxiv mpv ffmpeg imagemagick \
	fzf xwallpaper python-pywal unclutter xclip maim \
	zip unzip unrar p7zip xdotool papirus-icon-theme brightnessctl \
	dosfstools ntfs-3g git sxhkd fish pipewire net-tools \
	arc-gtk-theme alacritty lolcat neovim vim dash \
	xcompmgr libnotify dunst slock jq aria2 cowsay pacman-contrib \
	dhcpcd connman wpa_supplicant rsync pamixer mpd ncmpcpp \
	xdg-user-dirs libconfig sddm alsa-utils exa \
	bluez bluez-utils feh plymouth flameshot ninja meson uthash \
	clang shfmt

systemctl enable connman.service
systemctl enable sddm
systemctl enable networkmanager
echo "%wheel ALL=(ALL) NOPASSWD: ALL" >>/etc/sudoers

echo "Enter Username: "
read username
useradd -m -G wheel -s /bin/fish $username
passwd $username

ai3_path=/home/$username/arch_install3.sh
sed '1,/^#part3$/d' arch_install2.sh >$ai3_path
chown $username:$username $ai3_path
chmod +x $ai3_path
su -c $ai3_path -s /bin/sh $username
exit

echo "Pre-Installation Finish Reboot now"
#  add a timer and then autoreboot the pc